blendy_board/urls.py
from django.contrib import admin
from django.urls import path, include   # ←, includeを追加

urlpatterns = [
    path('', include('cms.urls')),   # ←ここを追加
    path('admin/', admin.site.urls),
]

cms/urls.py
from django.urls import path
from cms import views

app_name = 'cms'
urlpatterns = [
    # 書籍
    path('post/', views.post_list, name='post_list'),   # 一覧
    path('post/add/<int:parent>/', views.post_edit, name='post_add'),  # 登録
    path('post/mod/<int:post_id>/', views.post_edit, name='post_mod'),  # 修正
    path('post/del/<int:post_id>/', views.post_del, name='post_del'),   # 削除
    path('post/<int:post_id>/', views.post, name='post'),
]

cms/models.py
from django.db import models

class Post(models.Model):
    """投稿"""
    name = models.CharField('Title', max_length=255)
    author = models.CharField('Name', max_length=255)
    content = models.TextField('Contents', blank=True)
    parent = models.IntegerField('parent', default=0)
    update = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

# Create your models here.

cms/forms.py
from django.forms import ModelForm, HiddenInput
from cms.models import Post


class PostForm(ModelForm):
    """書籍のフォーム"""
    class Meta:
        model = Post
        fields = ('name', 'author', 'content', 'parent')
        widgets = {'parent': HiddenInput}

cms/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from cms.models import Post
from cms.forms import PostForm

def post(request, post_id=None):
    if post_id is None:
        posts = Post.objects.all().order_by('id').reverse()
        return render(request, 'cms/post_list.html', {'posts': posts})
    posts = Post.objects.filter(id=post_id).all()
    if len(posts) == 0:
        return redirect('/post')
    post = Post.objects.get(id=post_id)
    children = Post.objects.filter(parent=post_id).all().order_by('id')
    return render(request, 'cms/post.html', {'post': post, 'children': children})


def post_list(request):
    posts = Post.objects.filter(parent=0).all().order_by('id').reverse()
    return render(request, 'cms/post_list.html', {'posts': posts})


def post_edit(request, post_id=None, parent=None):
    if post_id:   # book_id が指定されている (修正時)
        post_check = Post.objects.filter(id=post_id).all()
        if len(post_check) == 0:
            return redirect('/post')
        post = get_object_or_404(Post, pk=post_id)
    else:         # book_id が指定されていない (追加時)
        post = Post()

    if request.method == 'POST':
        form = PostForm(request.POST, instance=post)  # POST された request データからフォームを作成
        if form.is_valid():    # フォpームのバリデーション
            post = form.save(commit=False)
            post.save()
            # return redirect('cms:post_list')
            if post.parent == 0:
                return redirect('/post/' + str(post.id))
            else:
                return redirect('/post/' +  str(post.parent))
    else:    # GET の時
        if parent is None:
            form = PostForm(instance=post)  # book インスタンスからフォームを作成
        else:
             form = PostForm(instance=post, initial={'parent': parent})  # book インスタンスからフォームを作成
    return render(request, 'cms/post_edit.html', dict(form=form, post_id=post_id, parent=parent))


def post_del(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    parent = post.parent
    post.delete()
    if parent == 0:
        return redirect('/post')
    else:
        return redirect('/post/' + str(parent))

cms/templates/cms/base.html
{% load i18n static %}
<!DOCTYPE html>{% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link rel="stylesheet" href="{% static 'cms/css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'cms/css/style.css' %}">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
{% block extra_css %}{% endblock %}
<title>{% block title %}My books{% endblock %}</title>
</head>
<body>
    <div class="header">
      <div class="menu">
          <i class="fas fa-bars"></i>
      </div>
      <div class="menu-content">
      </div>
    </div>
  <div class="container">
    {% block content %}
      {{ content }}
    {% endblock %}
  </div>
<script src="{% static 'cms/js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'cms/js/bootstrap.bundle.min.js' %}"></script>
{% block extra_js %}{% endblock %}
</body>
</html>

cms/templates/cms/post.html
{% extends "cms/base.html" %}

{% block title %}投稿一覧{% endblock title %}

{% block content %}
<div class="box11">
    <p class="content-title">{{ post.name }}</p>
    <p class="content-author">投稿者: {{ post.author }} | {{ post.update|date:"Y/m/d H:i" }}</p>
    {{ post.content|linebreaksbr }}
    <div class="button-below">
        <a href="{% url 'cms:post_mod' post_id=post.id %}" class="btn btn-outline-primary btn-sm">
            <i class="fas fa-edit"></i> edit
        </a>
        <a href="{% url 'cms:post_del' post_id=post.id %}" class="btn btn-outline-danger btn-sm">
            <i class="fas fa-trash-alt"></i> delete
        </a>
    </div>
</div>
{% for child in children %}
<div class="box11_child">
    <div class="post-reply">reply</div>
    <p class="content-title">{{ child.name }}</p>
    <p class="content-author">投稿者: {{ child.author }} | {{ child.update|date:"Y/m/d H:i" }}</p>
    {{ child.content|linebreaksbr }}
    <div class="button-below">
        <a href="{% url 'cms:post_mod' post_id=child.id %}" class="btn btn-outline-primary btn-sm">
            <i class="fas fa-edit"></i> edit
        </a>
        <a href="{% url 'cms:post_del' post_id=child.id %}" class="btn btn-outline-danger btn-sm">
            <i class="fas fa-trash-alt"></i> delete
        </a>
    </div>
    <!-- <div class="edit-button">
        <a href="{% url 'cms:post_mod' post_id=post.id %}" class="btn btn-outline-primary btn-sm">修正</a>
        <a href="{% url 'cms:post_del' post_id=post.id %}" class="btn btn-outline-danger btn-sm">削除</a>
    </div> -->
</div>
{% endfor %}
<a href="{% url 'cms:post_add' parent=post.id %}" class="btn-circle btn-reply">
    <i class="fas fa-comment"></i>
</a>
<a href="{% url 'cms:post_list'%}" class="btn-circle2 btn-back">
    <i class="fas fa-arrow-left"></i>
</a>
{% endblock content %}

cms/templates/cms/post_edit.html
{% extends "cms/base.html" %}
{% load bootstrap4 %}

{% block title %}書籍の編集{% endblock title %}

{% block content %}
    <h4 class="mt-4 mb-5 border-bottom">
      {% if parent == 0 %}
      新規投稿
      {% else %}
      返信
      {% endif %}
    </h4>
    {% if post_id %}
    <form action="{% url 'cms:post_mod' post_id=post_id %}" method="post">
    {% else %}
    <form action="{% url 'cms:post_add' parent=0 %}" method="post">
    {% endif %}
      {% csrf_token %}
      {% bootstrap_form form layout='horizontal' %}
      <div class="form-group row">
        <div class="offset-md-3 col-md-9">
          <button type="submit" class="btn btn-primary">送信</button>
        </div>
      </div>
    </form>
    <a href="{% url 'cms:post_list' %}" class="btn btn-secondary btn-sm">戻る</a>
{% endblock content %}

cms/templates/cms/post_list.html
{% extends "cms/base.html" %}

{% block title %}投稿一覧{% endblock title %}

{% block content %}
  <div class="list-title">- 投稿一覧 -</div>
    {% for post in posts %}
    <div class="box11">
      <div class="content-title">{{ post.name }}</div>
      <p class="content-author">投稿者: {{ post.author }} | {{ post.update|date:"Y/m/d H:i" }}</p>
      {{ post.content|linebreaksbr|truncatechars:50 }}
      <a class="box11_a" href="{% url 'cms:post' post_id=post.id %}"></a>
    </div>
    {% endfor %}
    <a href="{% url 'cms:post_add' parent=0%}" class="btn-circle btn-plus">
        <i class="fas fa-plus"></i>
    </a>
{% endblock content %}